export default {
    // Navigation
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_OTP: "/verify-otp",
    RESET_PASSWORD: "/reset-password", 
    PRODUCTS: "/products",
    HOME: "/",
    PRODUCT_DETAIL: "/product/:id",
    CART: "/cart",
    ORDERS: "/orders",
    PROFILE: "/profile",
    SETTINGS: "/settings",
    TERMS: "/terms",
    PRIVACY_POLICY: "/privacy-policy",
    ADMIN: "/admin",
    SELLER_APPLICATIONS: "/admin/seller-applications",
    SELLER: "/seller",
    SELLER_ORDERS: "/seller/orders",
    SELLER_ANALYTICS: "/seller/analytics",
    WISHLIST: "/wishlist",
    }